### ISSUE TITLE
Error @ uploading

### ISSUE THREAD

**Issue by mafudelaptu** [andrewelkins/cabinet#27]
If i try to upload an image i got following error:

Call to undefined method Intervention\Image\Image::make() in

vendor\andrewelkins\cabinet\src\Andrew13\Cabinet\CabinetUpload.php in line 276

**Comment by raykwok** [comment]
I have got the same error.

**Comment by carbontwelve** [comment]
I get the same error.

**Comment by andrewelkins** [comment]
Just merge the fix. Updating the version now.
